#!/bin/sh -e

# Build autoconf 2.13 for mozjs use.
# See: https://bugzilla.mozilla.org/show_bug.cgi?id=104642
(
    cd autoconf2.13
    ./configure --prefix="$PWD/../autoconf" --program-suffix=-2.13
    make
    make install
)
export PATH="$PWD/autoconf/bin:$PATH"


mkdir mozjs-build
cd mozjs-build

../js/src/configure \
    --prefix=/usr \
    --with-intl-api \
    --with-system-zlib \
    --disable-jemalloc \
    --enable-readline

make
make DESTDIR="$1" install
