#!/bin/sh -e

./configure \
    --prefix=/usr \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --with-drill \
    --disable-dane-ta-usage \
    --without-examples \
    --without-pyldns

make
make DESTDIR="$1" install
