#!/bin/sh -e

(
    cd cython

    python setup.py build_ext "-j$(nproc)"
    python setup.py install --root="$PWD/../junk" --optimize=1
)

export PYTHONPATH="$PWD/junk/usr/lib/python*/site-packages:$PYTHONPATH"

python setup.py build "-j$(nproc)"
python setup.py install --root="$1" --optimize=1

mkdir -p "$1/usr/share/man/man1"
cp ./docs/man/*.1 "$1/usr/share/man/man1"
