#!/bin/sh -e

cat << EOF

NOTE: 'borg' requires the Python 'packaging' module, it must be installed manually in order to run 'borg':

$ pip install packaging
# Or, in a Virtual Environment (to avoid clutter).
$ python -m venv ./path/to/my/env
$ . ./path/to/my/env/bin/activate
$ pip install packaging

EOF
