#!/bin/sh -e

cd wpa_supplicant

make LIBDIR=/usr/lib BINDIR=/usr/bin
make LIBDIR=/usr/lib BINDIR=/usr/bin DESTDIR="$1" install


install -v -d -m755 "$1/lib/systemd/system/"
install -v -m644 systemd/*.service "$1/lib/systemd/system/"

install -v -d -m755 "$1/usr/share/dbus-1/system-services/"
install -v -m644 dbus/fi.w1.wpa_supplicant1.service \
                 "$1/usr/share/dbus-1/system-services/"
install -v -d -m755 "$1/etc/dbus-1/system.d"
install -v -m644 dbus/dbus-wpa_supplicant.conf \
                 "$1/etc/dbus-1/system.d/wpa_supplicant.conf"

install -v -dm755 "$1/etc/wpa_supplicant"
install -v -m644 wpa_supplicant-wifi0.conf "$1/etc/wpa_supplicant/wpa_supplicant-wifi0.conf"
